# Generated by Django 6.1 on 2026-08-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre_auditor', models.CharField(max_length=100)),
                ('numero_cedula', models.CharField(max_length=10)),
                ('aplicativo', models.CharField(max_length=100)),
                ('fecha_operacion', models.DateField()),
                ('nombre_tecnico', models.CharField(max_length=200)),
                ('numero_cuenta_contrato', models.CharField(max_length=8)),
                ('numero_orden', models.CharField(max_length=10)),
                ('tipo_operacion', models.CharField(max_length=50)),
                ('resultado_auditoria', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'NO CUMPLE')], max_length=20)),
                ('observacion', models.TextField()),
                ('tipo_hallazgo', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20)),
                ('hallazgo', models.TextField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
