# Generated by Django 6.1 on 2026-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='numero_orden',
            field=models.CharField(max_length=11),
        ),
    ]
