# Generated by Django 6.1 on 2026-09-18 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='auditorias/evidencias/%Y/%m/', verbose_name='Foto de evidencia'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='origen',
            field=models.CharField(choices=[('excel', 'Cargue Excel'), ('manual', 'Registrada en el software')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Marca temporal'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_operacion',
            field=models.DateField(verbose_name='Fecha de operación'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='hallazgo',
            field=models.CharField(blank=True, choices=[('1.Medidor Erróneo', '1.Medidor Erróneo'), ('2.Fugas superior de a 1Vol', '2.Fugas superior de a 1Vol'), ('3.Troques de pdf', '3.Troques de pdf'), ('4.Foto original del ht', '4.Foto original del ht'), ('5.Lectura errónea', '5.Lectura errónea'), ('6.Anomalía', '6.Anomalía'), ('7.Precintado', '7.Precintado'), ('8.Troque de válvula', '8.Troque de válvula'), ('9.Tachones y enmendaduras en el HT', '9.Tachones y enmendaduras en el HT'), ('10.Sentido del maneral', '10.Sentido del maneral'), ('11.Sin anexos SAP', '11.Sin anexos SAP'), ('12.Falta o error de información en el ht', '12.Falta o error de información en el ht'), ('13.Retiro de material y residuos', '13.Retiro de material y residuos'), ('14.Pruebas con detector de fugas', '14.Pruebas con detector de fugas'), ('15.Prueba de estanqueidad', '15.Prueba de estanqueidad'), ('16.Diligenciamiento de datos en aplicativo', '16.Diligenciamiento de datos en aplicativo'), ('17.Registro fotográfico incompleto', '17.Registro fotográfico incompleto'), ('1.Anexos adicionales no correspondientes a la cuenta', '1.Anexos adicionales no correspondientes a la cuenta'), ('2.Justificación de falta material', '2.Justificación de falta material'), ('3.Foto acrílica', '3.Foto acrílica'), ('4.Observaciones de novedades', '4.Observaciones de novedades'), ('5.Diligenciamiento información del acrílico', '5.Diligenciamiento información del acrílico'), ('6.Registro fotográfico del centro medición y nicho antes de iniciar la operación', '6.Registro fotográfico del centro medición y nicho antes de iniciar la operación'), ('7.Foto de odómetro con lectura y número de medidor legible', '7.Foto de odómetro con lectura y número de medidor legible'), ('8.No relaciona material en el aplicativo SAP', '8.No relaciona material en el aplicativo SAP'), ('9.Copia ht', '9.Copia ht'), ('10.Registro fotográfico borrosas', '10.Registro fotográfico borrosas'), ('1.Color de marcador y esfero', '1.Color de marcador y esfero'), ('2.Acrílico deteriorado', '2.Acrílico deteriorado'), ('3.Calidad de fotos', '3.Calidad de fotos'), ('4.Stampa', '4.Stampa'), ('5.Foto fachada', '5.Foto fachada'), ('6.Observaciones en el aplicativo SAP', '6.Observaciones en el aplicativo SAP')], max_length=255, null=True, verbose_name='Hallazgo'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='numero_cuenta_contrato',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='numero_orden',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='observacion',
            field=models.TextField(verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='resultado_auditoria',
            field=models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_hallazgo',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_operacion',
            field=models.CharField(choices=[('ZVCL', 'ZVCL'), ('DC00', 'DC00'), ('RC00', 'RC00')], max_length=10),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cedula', models.CharField(max_length=10, unique=True, verbose_name='Número de cédula')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
