# Generated by Django 6.1 on 2026-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_alter_auditoria_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='hallazgo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_hallazgo',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo')], max_length=20),
        ),
    ]
