# Generated by Django 6.1 on 2026-09-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0002_alter_auditoria_options_auditoria_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
