# Generated by Django 6.1 on 2026-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0003_alter_auditoria_hallazgo_alter_auditoria_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='numero_cuenta_contrato',
            field=models.CharField(max_length=9),
        ),
    ]
