# Generated by Django 6.1 on 2026-09-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0004_alter_auditoria_aplicativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='origen',
            field=models.CharField(choices=[('excel', 'Cargue Excel'), ('manual', 'Auditorias SW')], default='manual', max_length=10),
        ),
    ]
