# Generated by Django 6.1 on 2026-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0006_alter_auditoria_tipo_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_operacion',
            field=models.CharField(choices=[('ZVCL', 'ZVCL'), ('DC00', 'DC00'), ('RC00', 'RC00')], max_length=10),
        ),
    ]
