# Generated by Django 6.1 on 2026-09-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorias', '0007_alter_auditoria_tipo_operacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='auditorias/evidencias/%Y/%m/', verbose_name='Foto de evidencia'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='origen',
            field=models.CharField(choices=[('excel', 'Cargue Excel'), ('manual', 'Registrada en el software')], default='manual', max_length=10, verbose_name='Origen del registro'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_carga',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='numero_orden',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
