# Generated by Django 6.1 on 2026-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=150)),
                ('tecnico_cedula', models.CharField(max_length=10, unique=True)),
                ('tecnico_apellido_nombres', models.CharField(max_length=150)),
            ],
        ),
    ]
