# Generated by Django 6.1 on 2026-09-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnicos',
            options={'verbose_name': 'Técnico', 'verbose_name_plural': 'Técnicos'},
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
