# Generated by Django 6.1 on 2026-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_alter_tecnicos_options_bitacora'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_carga_auditorias', models.DateTimeField(blank=True, null=True)),
                ('ultima_carga_tecnicos', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de carga',
                'verbose_name_plural': 'Estado de carga',
            },
        ),
    ]
